platform :ios, '8.0'

pod 'AFNetworking', '~> 2.0'

pod 'SDWebImage', '~>3.7'

pod 'MJExtension'

pod 'Reachability'

pod 'MJRefresh'

pod 'SVProgressHUD'

pod 'IQKeyboardManager'

pod 'FXBlurView'

pod 'CustomIOSAlertView'

pod 'UITableView+FDTemplateLayoutCell'

pod 'ReactiveCocoa', '~>2.3.1'

pod 'Realm'
