source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'

pod 'SDWebImage', '~>3.7'

pod 'MJExtension'

pod 'Reachability'

pod 'MJRefresh'

pod 'SVProgressHUD'